<?= $this->extend('layout') ?>
<?= $this->section('content') ?>
<div class="d-flex justify-content-between mb-3"><h2 class="h5"><?= esc($title) ?></h2><a href="/purchase-orders" class="btn btn-light">Kembali</a></div>
<form method="post" action="<?= esc($action) ?>" class="card" data-po-form><?= csrf_field() ?><div class="card-body row g-3">
<div class="col-md-4"><label class="form-label">Vendor *</label><select name="vendor_id" required class="form-select"><option value="">Pilih vendor</option><?php foreach($vendors as $v): ?><option value="<?= $v['id'] ?>" <?= ($po['vendor_id']??'')==$v['id']?'selected':'' ?>><?= esc($v['name']) ?></option><?php endforeach; ?></select></div>
<div class="col-md-4"><label class="form-label">Nomor PO *</label><input name="po_no" required class="form-control" value="<?= esc($po['po_no']??'PO-'.date('YmdHis')) ?>"></div>
<div class="col-md-2"><label class="form-label">Tanggal</label><input type="date" name="po_date" class="form-control" value="<?= esc($po['po_date']??date('Y-m-d')) ?>"></div>
<div class="col-md-2"><label class="form-label">Status</label><select name="status" class="form-select"><option value="draft">Draft</option><option value="sent" <?= ($po['status']??'')==='sent'?'selected':'' ?>>Dikirim</option><option value="approved" <?= ($po['status']??'')==='approved'?'selected':'' ?>>Disetujui</option></select></div>
<div class="col-12"><div class="d-flex justify-content-between align-items-center mb-2"><h6 class="mb-0">Item Produk</h6><button type="button" class="btn btn-sm btn-outline-primary" data-po-add><i class="bi bi-plus-lg me-1"></i>Tambah produk</button></div><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th style="min-width:260px">Produk katalog</th><th>Deskripsi</th><th style="width:100px">Qty</th><th style="width:110px">Satuan</th><th style="width:160px">Harga beli</th><th style="width:50px"></th></tr></thead><tbody data-po-items><?php $items=$po['items']??[[]];foreach($items as $i=>$item): ?><tr data-po-row><td><select name="items[<?= $i ?>][product_id]" class="form-select" data-po-product required><option value="">Pilih produk</option><?php foreach($products as $p): ?><option value="<?= $p['id'] ?>" data-price="<?= esc($p['selling_price']??0) ?>" data-unit="<?= esc($p['unit']??'pcs') ?>" <?= (int)($item['product_id']??0)===(int)$p['id']?'selected':'' ?>><?= esc(($p['brand']?$p['brand'].' / ':'').$p['name']) ?></option><?php endforeach; ?></select></td><td><input name="items[<?= $i ?>][description]" class="form-control" value="<?= esc($item['description']??'') ?>"></td><td><input type="number" step="0.01" min="0.01" name="items[<?= $i ?>][quantity]" class="form-control" value="<?= esc($item['quantity']??1) ?>"></td><td><input name="items[<?= $i ?>][unit]" class="form-control" value="<?= esc($item['unit']??'pcs') ?>"></td><td><input type="number" step="0.01" min="0" name="items[<?= $i ?>][unit_price]" class="form-control" value="<?= esc($item['unit_price']??0) ?>"></td><td><button type="button" class="btn btn-sm btn-outline-danger" data-po-remove title="Hapus baris"><i class="bi bi-trash3"></i></button></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="col-12"><hr><h6>Pajak Pembelian</h6></div><div class="col-md-3 form-check ms-2"><input class="form-check-input" type="checkbox" name="use_ppn" value="1" id="use_ppn" <?= !empty($po['use_ppn'])?'checked':'' ?>><label class="form-check-label" for="use_ppn">Gunakan PPN</label></div><div class="col-md-3"><label class="form-label">PPN (%)</label><input type="number" step="0.01" min="0" name="ppn_percent" class="form-control" value="<?= esc($po['ppn_percent']??11) ?>"></div><div class="col-md-3 form-check ms-2"><input class="form-check-input" type="checkbox" name="use_pph" value="1" id="use_pph" <?= !empty($po['use_pph'])?'checked':'' ?>><label class="form-check-label" for="use_pph">Gunakan PPh</label></div><div class="col-md-3"><label class="form-label">PPh (%)</label><input type="number" step="0.01" min="0" name="pph_percent" class="form-control" value="<?= esc($po['pph_percent']??0) ?>"></div>
<div class="col-12"><label class="form-label">Catatan</label><textarea name="notes" class="form-control"><?= esc($po['notes']??'') ?></textarea></div></div><div class="card-footer"><button class="btn btn-primary"><i class="bi bi-save me-1"></i>Simpan PO</button></div></form>
<script>document.addEventListener('DOMContentLoaded',()=>{const form=document.querySelector('[data-po-form]');if(!form)return;const body=form.querySelector('[data-po-items]');let n=body.querySelectorAll('[data-po-row]').length;const options=<?= json_encode(array_map(static fn($p)=>['id'=>$p['id'],'label'=>($p['brand']?$p['brand'].' / ':'').$p['name'],'price'=>$p['selling_price']??0,'unit'=>$p['unit']??'pcs'], $products), JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP) ?>;const row=(i)=>{const o=options.map(p=>`<option value="${p.id}" data-price="${p.price}" data-unit="${p.unit}">${p.label}</option>`).join('');return `<tr data-po-row><td><select name="items[${i}][product_id]" class="form-select" data-po-product required><option value="">Pilih produk</option>${o}</select></td><td><input name="items[${i}][description]" class="form-control"></td><td><input type="number" step="0.01" min="0.01" name="items[${i}][quantity]" class="form-control" value="1"></td><td><input name="items[${i}][unit]" class="form-control" value="pcs"></td><td><input type="number" step="0.01" min="0" name="items[${i}][unit_price]" class="form-control" value="0"></td><td><button type="button" class="btn btn-sm btn-outline-danger" data-po-remove><i class="bi bi-trash3"></i></button></td></tr>`};form.addEventListener('click',e=>{if(e.target.closest('[data-po-add]'))body.insertAdjacentHTML('beforeend',row(n++));if(e.target.closest('[data-po-remove]')){const rows=body.querySelectorAll('[data-po-row]');if(rows.length>1)e.target.closest('[data-po-row]').remove();}});form.addEventListener('change',e=>{const s=e.target.closest('[data-po-product]');if(!s)return;const o=s.selectedOptions[0];const r=s.closest('[data-po-row]');if(o?.dataset.price)r.querySelector('[name$="[unit_price]"]').value=o.dataset.price;if(o?.dataset.unit)r.querySelector('[name$="[unit]"]').value=o.dataset.unit;});});</script>
<?= $this->endSection() ?>
