<?= $this->extend('layout') ?>
<?= $this->section('content') ?>
<div class="d-flex justify-content-between mb-3"><h2 class="h5"><?= esc($title) ?></h2><a href="/vendor-bills" class="btn btn-light">Kembali</a></div>
<form method="post" enctype="multipart/form-data" action="<?= esc($action) ?>" class="card" data-vendor-bill-form><div class="card-body row g-3"><?= csrf_field() ?>
<div class="col-md-4"><label class="form-label">Vendor *</label><select name="vendor_id" required class="form-select"><option value="">Pilih vendor</option><?php foreach($vendors as $v): ?><option value="<?= $v['id'] ?>" <?= ($bill['vendor_id']??'')==$v['id']?'selected':'' ?>><?= esc($v['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Nomor Tagihan *</label><input name="bill_no" required class="form-control" value="<?= esc($bill['bill_no']??'') ?>"></div><div class="col-md-2"><label class="form-label">Tanggal</label><input type="date" name="bill_date" class="form-control" value="<?= esc($bill['bill_date']??date('Y-m-d')) ?>"></div><div class="col-md-2"><label class="form-label">Jatuh Tempo</label><input type="date" name="due_date" class="form-control" value="<?= esc($bill['due_date']??'') ?>"></div>
<div class="col-md-4"><label class="form-label">DPP / Nilai Dasar Tagihan</label><input type="number" step="0.01" name="amount" class="form-control" value="<?= esc($bill['amount']??0) ?>"></div><div class="col-md-4"><label class="form-label">Status</label><select name="status" class="form-select"><option value="unpaid" <?= ($bill['status']??'unpaid')==='unpaid'?'selected':'' ?>>Belum dibayar</option><option value="partial" <?= ($bill['status']??'')==='partial'?'selected':'' ?>>Dibayar sebagian</option><option value="paid" <?= ($bill['status']??'')==='paid'?'selected':'' ?>>Sudah dibayar</option></select></div><div class="col-md-4"><label class="form-label">Tanggal Bayar</label><input type="date" name="paid_date" class="form-control" value="<?= esc($bill['paid_date']??'') ?>"></div>
<div class="col-12"><hr><h6>Perhitungan Pajak</h6></div><div class="col-md-3 form-check ms-2"><input class="form-check-input" type="checkbox" name="use_ppn" value="1" id="bill_use_ppn" <?= !empty($bill['use_ppn'])?'checked':'' ?>><label class="form-check-label" for="bill_use_ppn">Gunakan PPN</label></div><div class="col-md-3"><label class="form-label">PPN (%)</label><input type="number" step="0.01" min="0" name="ppn_percent" class="form-control" value="<?= esc($bill['ppn_percent']??11) ?>"></div><div class="col-md-3 form-check ms-2"><input class="form-check-input" type="checkbox" name="use_pph" value="1" id="bill_use_pph" <?= !empty($bill['use_pph'])?'checked':'' ?>><label class="form-check-label" for="bill_use_pph">Gunakan PPh</label></div><div class="col-md-3"><label class="form-label">PPh (%)</label><input type="number" step="0.01" min="0" name="pph_percent" class="form-control" value="<?= esc($bill['pph_percent']??0) ?>"></div><div class="col-12"><div class="alert alert-light border mb-0">Nilai bersih = DPP + PPN - PPh. Perhitungan disimpan otomatis saat form disimpan.</div></div>
<div class="col-md-6"><label class="form-label">Referensi Pembayaran</label><input name="payment_reference" class="form-control" value="<?= esc($bill['payment_reference']??'') ?>"></div><div class="col-md-6"><label class="form-label">Bukti Pembayaran</label><input type="file" name="proof" class="form-control" accept=".jpg,.jpeg,.png,.webp,.pdf"><?php if(!empty($bill['proof_path'])): ?><a href="<?= esc($bill['proof_path']) ?>" target="_blank">Lihat bukti</a><?php endif; ?></div><div class="col-12"><label class="form-label">Catatan</label><textarea name="notes" class="form-control"><?= esc($bill['notes']??'') ?></textarea></div></div><div class="card-footer"><button class="btn btn-primary">Simpan Tagihan</button></div></form>
<?= $this->endSection() ?>
