-- Jalankan setelah database/eprocurement.sql dan migrasi quotation/auth.
-- Migration CodeIgniter utama: 2026-09-24-000008_CreateFinanceProcurementModules.php
-- File ini disediakan sebagai SQL pendamping instalasi manual. Jalankan hanya sekali.
CREATE TABLE IF NOT EXISTS proforma_invoices (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, quotation_id INT UNSIGNED NOT NULL, invoice_no VARCHAR(80) NOT NULL UNIQUE, invoice_date DATE NOT NULL, due_date DATE NULL, amount DECIMAL(18,2) NOT NULL DEFAULT 0, payment_status VARCHAR(20) NOT NULL DEFAULT 'unpaid', payment_date DATE NULL, payment_method VARCHAR(80) NULL, payment_reference VARCHAR(160) NULL, proof_path VARCHAR(500) NULL, notes TEXT NULL, created_at DATETIME NULL, updated_at DATETIME NULL, INDEX (quotation_id), CONSTRAINT fk_proforma_quotation FOREIGN KEY (quotation_id) REFERENCES quotations(id) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS vendors (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(180) NOT NULL, code VARCHAR(60) NULL, address TEXT NULL, phone VARCHAR(80) NULL, email VARCHAR(160) NULL, pic_name VARCHAR(120) NULL, payment_terms VARCHAR(255) NULL, notes TEXT NULL, is_active TINYINT NOT NULL DEFAULT 1, created_at DATETIME NULL, updated_at DATETIME NULL, INDEX(name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS purchase_orders (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, vendor_id INT UNSIGNED NOT NULL, po_no VARCHAR(80) NOT NULL UNIQUE, po_date DATE NOT NULL, expected_date DATE NULL, status VARCHAR(20) NOT NULL DEFAULT 'draft', subtotal DECIMAL(18,2) NOT NULL DEFAULT 0, tax_percent DECIMAL(5,2) NOT NULL DEFAULT 0, tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0, grand_total DECIMAL(18,2) NOT NULL DEFAULT 0, notes TEXT NULL, created_at DATETIME NULL, updated_at DATETIME NULL, INDEX(vendor_id), CONSTRAINT fk_po_vendor FOREIGN KEY(vendor_id) REFERENCES vendors(id) ON DELETE RESTRICT ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS purchase_order_items (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, purchase_order_id INT UNSIGNED NOT NULL, product_id INT UNSIGNED NULL, product_name VARCHAR(180) NOT NULL, description TEXT NULL, quantity DECIMAL(18,2) NOT NULL DEFAULT 1, unit VARCHAR(30) NOT NULL DEFAULT 'pcs', unit_price DECIMAL(18,2) NOT NULL DEFAULT 0, line_total DECIMAL(18,2) NOT NULL DEFAULT 0, INDEX(purchase_order_id), CONSTRAINT fk_poi_po FOREIGN KEY(purchase_order_id) REFERENCES purchase_orders(id) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS vendor_bills (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, vendor_id INT UNSIGNED NOT NULL, purchase_order_id INT UNSIGNED NULL, bill_no VARCHAR(80) NOT NULL UNIQUE, bill_date DATE NOT NULL, due_date DATE NULL, amount DECIMAL(18,2) NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'unpaid', paid_date DATE NULL, payment_reference VARCHAR(160) NULL, proof_path VARCHAR(500) NULL, notes TEXT NULL, created_at DATETIME NULL, updated_at DATETIME NULL, INDEX(vendor_id), CONSTRAINT fk_bill_vendor FOREIGN KEY(vendor_id) REFERENCES vendors(id) ON DELETE RESTRICT ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS notifications (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NULL, type VARCHAR(40) NOT NULL, title VARCHAR(180) NOT NULL, message TEXT NOT NULL, url VARCHAR(500) NULL, due_at DATETIME NULL, is_read TINYINT NOT NULL DEFAULT 0, created_at DATETIME NULL, INDEX(user_id,is_read)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- Permission rows are inserted by the CodeIgniter migration to remain idempotent.
