<?php
namespace App\Controllers;
use App\Models\ProformaInvoiceModel; use App\Models\QuotationModel;
class ProformaInvoices extends BaseController
{
 private ProformaInvoiceModel $model; public function __construct(){ $this->model=new ProformaInvoiceModel(); }
 public function index(){return view('proforma/index',['title'=>'Proforma Invoice']);}
 public function datatable(){ $r=$this->request->getGet();$q=trim((string)($r['search']['value']??''));$rows=$this->model->withQuotation();if($q)$rows=array_values(array_filter($rows,static fn($x)=>stripos($x['invoice_no'].' '.$x['quotation_no'].' '.$x['company_name'],$q)!==false));$data=array_map(static function($x){$id=public_id((int)$x['id']);$status=['paid'=>'success','partial'=>'warning','unpaid'=>'danger'][$x['payment_status']]??'secondary';$a='<div class="dropdown datatable-actions"><button class="btn btn-sm btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown">Aksi</button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="/proforma-invoices/'.$id.'/edit"><i class="bi bi-cash-coin me-2"></i>Kelola pembayaran</a></li><li><a class="dropdown-item" href="/quotations/'.public_id((int)$x['quotation_id']).'/proforma-invoice"><i class="bi bi-file-earmark-pdf me-2"></i>Unduh PDF</a></li></ul></div>';return ['invoice_no'=>'<strong>'.esc($x['invoice_no']).'</strong><div class="small text-body-secondary">'.esc($x['quotation_no']).'</div>','customer'=>esc($x['company_name']),'amount'=>'Rp '.number_format((float)$x['amount'],0,',','.'),'due'=>esc($x['due_date']??'-'),'status'=>'<span class="badge text-bg-'.$status.'">'.esc(ucfirst($x['payment_status'])).'</span>','actions'=>$a];},$rows);return $this->response->setJSON(['draw'=>(int)($r['draw']??0),'recordsTotal'=>count($rows),'recordsFiltered'=>count($rows),'data'=>$data]); }
 public function edit(string $id){$id=$this->resolveId($id,$this->model);return view('proforma/form',['title'=>'Kelola Pembayaran Proforma','invoice'=>$this->model->find($id),'action'=>'/proforma-invoices/'.public_id($id)]);}
 public function update(string $id){$id=$this->resolveId($id,$this->model);$data=$this->request->getPost(['payment_status','payment_date','payment_method','payment_reference','notes']);$file=$this->request->getFile('proof');if($file&&$file->isValid()&&!$file->hasMoved()){if($file->getSize()>5242880||!in_array(strtolower($file->getExtension()),['jpg','jpeg','png','webp','pdf'],true))return redirect()->back()->withInput()->with('error','Bukti bayar harus JPG, PNG, WEBP, atau PDF maksimal 5 MB.');$dir=FCPATH.'uploads/payment-proofs';if(!is_dir($dir))mkdir($dir,0755,true);$name=$file->getRandomName();$file->move($dir,$name);$data['proof_path']='/uploads/payment-proofs/'.$name;}if($data['payment_status']==='paid'&&!$data['payment_date'])$data['payment_date']=date('Y-m-d');$this->model->update($id,$data);return redirect()->to('/proforma-invoices')->with('message','Status pembayaran proforma berhasil diperbarui.');}
 public function syncApproved(){foreach((new QuotationModel())->where('status','approved')->findAll() as $q){if(!$this->model->where('quotation_id',$q['id'])->first())$this->model->insert(['quotation_id'=>$q['id'],'invoice_no'=>'PI-'.$q['quotation_no'],'invoice_date'=>date('Y-m-d'),'due_date'=>date('Y-m-d',strtotime('+30 days')),'amount'=>$q['grand_total'],'payment_status'=>'unpaid','created_at'=>date('Y-m-d H:i:s')]);}return redirect()->to('/proforma-invoices');}
}
