<?php
namespace App\Controllers;
use App\Models\PurchaseOrderModel; use App\Models\PurchaseOrderItemModel; use App\Models\VendorModel; use App\Models\ProductModel;
class PurchaseOrders extends BaseController
{
 private PurchaseOrderModel $model; public function __construct(){ $this->model=new PurchaseOrderModel(); }
 public function index(){return view('purchase_orders/index',['title'=>'Purchase Order']);}
 public function datatable(){ $r=$this->request->getGet();$rows=$this->model->withVendor();$data=array_map(static function($x){$id=public_id((int)$x['id']);$a='<div class="dropdown datatable-actions"><button class="btn btn-sm btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown">Aksi</button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="/purchase-orders/'.$id.'/edit"><i class="bi bi-pencil me-2"></i>Edit PO</a></li><li><form method="post" action="/purchase-orders/'.$id.'/delete" data-confirm data-confirm-title="Hapus PO?">'.csrf_field().'<button class="dropdown-item text-danger"><i class="bi bi-trash me-2"></i>Hapus PO</button></form></li></ul></div>';return ['po_no'=>'<strong>'.esc($x['po_no']).'</strong>','vendor'=>esc($x['vendor_name']),'date'=>esc($x['po_date']),'amount'=>'Rp '.number_format((float)$x['grand_total'],0,',','.'),'status'=>'<span class="badge text-bg-'.($x['status']==='approved'?'success':'secondary').'">'.esc(ucfirst($x['status'])).'</span>','actions'=>$a];},$rows);return $this->response->setJSON(['draw'=>(int)($r['draw']??0),'recordsTotal'=>count($data),'recordsFiltered'=>count($data),'data'=>$data]); }
 public function new(){return view('purchase_orders/form',['title'=>'Tambah Purchase Order','po'=>[],'vendors'=>(new VendorModel())->where('is_active',1)->findAll(),'products'=>(new ProductModel())->findAll(),'action'=>'/purchase-orders']);}
 public function edit(string $id){$id=$this->resolveId($id,$this->model);return view('purchase_orders/form',['title'=>'Edit Purchase Order','po'=>$this->model->detail($id),'vendors'=>(new VendorModel())->findAll(),'products'=>(new ProductModel())->findAll(),'action'=>'/purchase-orders/'.public_id($id)]);}
 public function save(?string $id=null){$id=$id?$this->resolveId($id,$this->model):null;$items=(array)$this->request->getPost('items');$valid=[];$subtotal=0;foreach($items as $item){$qty=(float)($item['quantity']??0);$price=(float)($item['unit_price']??0);if($qty<=0)continue;$line=$qty*$price;$subtotal+=$line;$valid[]=['product_id'=>(int)($item['product_id']??0)?:null,'product_name'=>trim((string)($item['product_name']??'')),'description'=>trim((string)($item['description']??'')),'quantity'=>$qty,'unit'=>trim((string)($item['unit']??'pcs'))?:'pcs','unit_price'=>$price,'line_total'=>$line];}if(!$this->request->getPost('vendor_id')||!$valid)return redirect()->back()->withInput()->with('errors',['items'=>'Vendor dan minimal satu item wajib diisi.']);$tax=(float)$this->request->getPost('tax_percent');$data=$this->request->getPost(['vendor_id','po_no','po_date','expected_date','status','tax_percent','notes']);$data['tax_percent']=$tax;$data['subtotal']=$subtotal;$data['tax_amount']=$subtotal*$tax/100;$data['grand_total']=$subtotal+$data['tax_amount'];$data['created_at']=date('Y-m-d H:i:s');$db=db_connect();$db->transStart();if($id){$this->model->update($id,$data);$poId=$id;(new PurchaseOrderItemModel())->where('purchase_order_id',$id)->delete();}else{$poId=$this->model->insert($data,true);}foreach($valid as &$item)$item['purchase_order_id']=$poId;(new PurchaseOrderItemModel())->insertBatch($valid);$db->transComplete();return redirect()->to('/purchase-orders')->with('message','Purchase Order berhasil disimpan.');}
 public function delete(string $id){$id=$this->resolveId($id,$this->model);$this->model->delete($id);return redirect()->to('/purchase-orders')->with('message','Purchase Order dihapus.');}
}
