<?php
namespace App\Controllers;
use App\Models\VendorBillModel; use App\Models\VendorModel;
class VendorBills extends BaseController
{
 private VendorBillModel $model; public function __construct(){ $this->model=new VendorBillModel(); }
 public function index(){return view('vendor_bills/index',['title'=>'Tagihan Vendor']);}
 public function datatable(){ $r=$this->request->getGet();$rows=$this->model->withVendor();$data=array_map(static function($x){$id=public_id((int)$x['id']);$c=$x['status']==='paid'?'success':($x['status']==='partial'?'warning':'danger');$a='<div class="dropdown datatable-actions"><button class="btn btn-sm btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown">Aksi</button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="/vendor-bills/'.$id.'/edit"><i class="bi bi-cash-coin me-2"></i>Kelola tagihan</a></li></ul></div>';return ['bill_no'=>'<strong>'.esc($x['bill_no']).'</strong><div class="small">PO: '.esc($x['po_no']??'-').'</div>','vendor'=>esc($x['vendor_name']),'amount'=>'Rp '.number_format((float)($x['net_amount']?:$x['amount']),0,',','.'),'due'=>esc($x['due_date']??'-'),'status'=>'<span class="badge text-bg-'.$c.'">'.esc(ucfirst($x['status'])).'</span>','actions'=>$a];},$rows);return $this->response->setJSON(['draw'=>(int)($r['draw']??0),'recordsTotal'=>count($data),'recordsFiltered'=>count($data),'data'=>$data]); }
 public function new(){return view('vendor_bills/form',['title'=>'Tambah Tagihan Vendor','bill'=>[],'vendors'=>(new VendorModel())->where('is_active',1)->findAll(),'action'=>'/vendor-bills']);}
 public function edit(string $id){$id=$this->resolveId($id,$this->model);return view('vendor_bills/form',['title'=>'Edit Tagihan Vendor','bill'=>$this->model->find($id),'vendors'=>(new VendorModel())->findAll(),'action'=>'/vendor-bills/'.public_id($id)]);}
 public function save(?string $id=null){$id=$id?$this->resolveId($id,$this->model):null;$data=$this->request->getPost(['vendor_id','purchase_order_id','bill_no','bill_date','due_date','amount','status','paid_date','payment_reference','notes']);$amount=(float)($data['amount']??0);$usePpn=$this->request->getPost('use_ppn')?1:0;$ppnPercent=(float)$this->request->getPost('ppn_percent');$usePph=$this->request->getPost('use_pph')?1:0;$pphPercent=(float)$this->request->getPost('pph_percent');$data+=['use_ppn'=>$usePpn,'ppn_percent'=>$ppnPercent,'ppn_amount'=>$usePpn?$amount*$ppnPercent/100:0,'use_pph'=>$usePph,'pph_percent'=>$pphPercent,'pph_amount'=>$usePph?$amount*$pphPercent/100:0];$data['net_amount']=$amount+$data['ppn_amount']-$data['pph_amount'];if(!$data['vendor_id']||!$data['bill_no'])return redirect()->back()->withInput()->with('errors',['bill_no'=>'Vendor dan nomor tagihan wajib diisi.']);$file=$this->request->getFile('proof');if($file&&$file->isValid()&&!$file->hasMoved()){if($file->getSize()>5242880)return redirect()->back()->withInput()->with('error','Bukti pembayaran maksimal 5 MB.');$dir=FCPATH.'uploads/payment-proofs';if(!is_dir($dir))mkdir($dir,0755,true);$name=$file->getRandomName();$file->move($dir,$name);$data['proof_path']='/uploads/payment-proofs/'.$name;}$id?$this->model->update($id,$data):$this->model->insert($data);return redirect()->to('/vendor-bills')->with('message','Tagihan vendor berhasil disimpan.');}
 public function delete(string $id){$id=$this->resolveId($id,$this->model);$this->model->delete($id);return redirect()->to('/vendor-bills')->with('message','Tagihan vendor dihapus.');}
}
