<!doctype html>
<html lang="id"><head><meta charset="utf-8"><style>
@page{margin:28px 32px}body{font-family:DejaVu Sans,sans-serif;color:#1f2937;font-size:10px}h1{margin:0 0 4px;font-size:20px;color:#0f3d67}h2{margin:0 0 3px;font-size:16px;color:#fff}h3{margin:14px 0 5px;font-size:11px;color:#0f3d67}p{margin:4px 0;line-height:1.4}.header{border-bottom:2px solid #0f3d67;padding-bottom:9px;margin-bottom:18px}.logo{max-width:135px;max-height:50px}.muted{color:#64748b}.banner{background:#0f3d67;color:#fff;padding:10px 12px;margin-bottom:12px}.banner p{margin:2px 0 0;font-size:9px}.product-table,.spec-table{width:100%;border-collapse:collapse}.product-table td{vertical-align:top}.image-cell{width:160px;text-align:center;padding-right:14px}.product-image{max-width:145px;max-height:145px}.spec-table{margin-top:5px}.spec-table td{border:1px solid #b8c1cc;padding:5px 7px;vertical-align:top}.spec-table td:first-child{width:30%;background:#edf0f3;font-weight:bold;color:#374151}.footer{margin-top:22px;padding-top:7px;border-top:1px solid #cbd5e1;color:#64748b;font-size:8px}
</style></head><body>
<div class="header"><?php if ($logoData): ?><img src="<?= $logoData ?>" class="logo" alt="Logo"><br><?php endif; ?><h1>Katalog Produk</h1><p class="muted"><?= esc($settings['company_name'] ?? '') ?></p></div>
<div class="banner"><h2><?= esc($product['name']) ?></h2><p><?= esc($product['brand'] ?? '') ?><?= !empty($product['brand']) && !empty($product['sku']) ? ' · ' : '' ?><?= esc($product['sku'] ?? '') ?></p></div>
<table class="product-table"><tr><td class="image-cell"><?php if ($imageData): ?><img src="<?= $imageData ?>" class="product-image" alt="Produk"><?php else: ?><span class="muted">Tidak ada gambar</span><?php endif; ?></td><td><p><?= nl2br(esc($product['description'] ?? '')) ?></p></td></tr></table>
<?php $rawSpecs = json_decode($product['technical_specs'] ?? '', true) ?: []; if (is_array($rawSpecs) && (array_key_exists('label', $rawSpecs) || array_key_exists('value', $rawSpecs))) $rawSpecs = [$rawSpecs]; $specs = []; foreach ((array) $rawSpecs as $key => $spec) { $label = is_array($spec) ? trim((string) ($spec['label'] ?? $key)) : trim((string) $key); $value = is_array($spec) ? trim((string) ($spec['value'] ?? '')) : (is_scalar($spec) ? trim((string) $spec) : trim((string) json_encode($spec))); if ($label !== '' && $value !== '') $specs[] = ['label' => $label, 'value' => $value]; } ?>
<?php if ($specs): ?><h3>Spesifikasi Teknis</h3><table class="spec-table"><?php foreach ($specs as $spec): ?><tr><td><?= esc($spec['label']) ?></td><td><?= nl2br(esc($spec['value'])) ?></td></tr><?php endforeach; ?></table><?php endif; ?>
<?php if (!empty($product['applications']) || !empty($product['standards']) || !empty($product['datasheet'])): ?><h3>Informasi Produk</h3><table class="spec-table"><?php if (!empty($product['applications'])): ?><tr><td>Aplikasi / Fungsi</td><td><?= nl2br(esc($product['applications'])) ?></td></tr><?php endif; ?><?php if (!empty($product['standards'])): ?><tr><td>Standar / Sertifikasi</td><td><?= nl2br(esc($product['standards'])) ?></td></tr><?php endif; ?><?php if (!empty($product['datasheet'])): ?><tr><td>Catatan Datasheet</td><td><?= nl2br(esc($product['datasheet'])) ?></td></tr><?php endif; ?></table><?php endif; ?>
<div class="footer">Dokumen katalog dibuat dari data produk <?= esc($product['name']) ?>.</div></body></html>
